//! Shared identifiers, time buckets, and error helpers used across the
//! workspace. No networking, no crypto — those live in dedicated crates.

pub mod framing;

use serde::{Deserialize, Serialize};
use std::fmt;
use std::time::{SystemTime, UNIX_EPOCH};

/// Opaque identifier for a transport family (e.g. "direct-tls").
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Serialize, Deserialize)]
pub struct TransportId(&'static str);

impl TransportId {
    pub const fn new(id: &'static str) -> Self {
        Self(id)
    }
    pub fn as_str(&self) -> &'static str {
        self.0
    }
}

impl fmt::Display for TransportId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Opaque identifier for a relay endpoint, generated by the operator/
/// rendezvous service. Never derived from a raw IP so logs/telemetry can
/// reference an endpoint without necessarily embedding its address.
#[derive(Clone, PartialEq, Eq, Hash, Debug, Serialize, Deserialize)]
pub struct EndpointId(pub String);

impl fmt::Display for EndpointId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Unix seconds. Kept as a plain newtype (not `SystemTime`) so it is
/// trivially serializable and comparable in signed bundles.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Serialize, Deserialize)]
pub struct UnixSeconds(pub u64);

impl UnixSeconds {
    pub fn now() -> Self {
        let secs = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock before Unix epoch")
            .as_secs();
        Self(secs)
    }

    pub fn saturating_add_secs(self, secs: u64) -> Self {
        Self(self.0.saturating_add(secs))
    }
}

/// Coarse duration bucket for telemetry / scoring — never a raw millisecond
/// value, to keep timing data coarse-grained by construction.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize)]
pub enum DurationBucket {
    Under100Ms,
    Under500Ms,
    Under2s,
    Under10s,
    Over10s,
}

impl DurationBucket {
    pub fn from_millis(ms: u128) -> Self {
        match ms {
            0..=99 => Self::Under100Ms,
            100..=499 => Self::Under500Ms,
            500..=1999 => Self::Under2s,
            2000..=9999 => Self::Under10s,
            _ => Self::Over10s,
        }
    }
}

#[derive(thiserror::Error, Debug)]
pub enum CommonError {
    #[error("value out of range: {0}")]
    OutOfRange(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn duration_bucket_boundaries() {
        assert!(matches!(
            DurationBucket::from_millis(0),
            DurationBucket::Under100Ms
        ));
        assert!(matches!(
            DurationBucket::from_millis(99),
            DurationBucket::Under100Ms
        ));
        assert!(matches!(
            DurationBucket::from_millis(100),
            DurationBucket::Under500Ms
        ));
        assert!(matches!(
            DurationBucket::from_millis(2000),
            DurationBucket::Under10s
        ));
        assert!(matches!(
            DurationBucket::from_millis(50_000),
            DurationBucket::Over10s
        ));
    }

    #[test]
    fn unix_seconds_monotonic_add() {
        let t = UnixSeconds(10);
        assert_eq!(t.saturating_add_secs(5).0, 15);
        assert_eq!(UnixSeconds(u64::MAX).saturating_add_secs(5).0, u64::MAX);
    }
}
